name: sim_data_new
description: A Flutter plugin to retrieve Sim cards data - dual sim support - only Android for now.
version: 1.0.0
homepage: https://github.com/inossan-dev/sim_data_new.git
documentation: https://github.com/inossan-dev/sim_data_new.git
repository: https://github.com/inossan-dev/sim_data_new.git
issue_tracker: https://github.com/inossan-dev/sim_data_new/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ino.sim_data_new
        pluginClass: SimDataPlugin